version: "3.7"
services:
  backend:
    image: qhuong1008/mori-backend
    networks:
      - backend_network
    environment:
      ACCESS_TOKEN_SECRET: Access_Token_Secret_Mori
      ACCESS_TOKEN_LIFE: 10m

      EMAIL_SERVICE: Gmail
      EMAIL_USER: bischlien@gmail.com
      EMAIL_PASS: rjtshtoqxlfvloip
      JWT_SECRET: jwtMoriBook
      JWT_SECRET_ALLOW_ORIGIN: hcmutefitmoriauth

      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=moristorage123;AccountKey=aC4C/1nK1LktBTWifiMLF6dY7v8rxxbNcf+DQcQgDme+J1pZ+2Ojw5xAt6gUnC6krivcsHLN+EwS+AStSMMNgQ==;EndpointSuffix=core.windows.net
      AZURE_STORAGE_CONTAINER_NAME_IMG: bookimg
      AZURE_STORAGE_CONTAINER_NAME_PDF: bookpdf
      AZURE_STORAGE_CONTAINER_NAME_AUDIO: bookaudio
      AZURE_STORAGE_CONTAINER_NAME_AVATAR: accountimg
      MONGODB_URL: mongodb+srv://moribook:Mori123456@cluster0.xdqbzc5.mongodb.net/moridb
      ALLOW_ORIGIN_TOKEN: huonglienhcmutefit123
      FRONTEND_URL: https://ebook.workon.space
      BACKEND_URL: https://ebook.workon.space
      ADMIN_URL: https://ebook.workon.space
      NLP_URL: https://ebook.workon.space
      FPT_API_KEY: fL8pbnvvIQhak30mjZALVBAAH2bhozwK

  frontend:
    image: qhuong1008/mori-frontend
    networks:
      - backend_network
    environment:
      GOOGLE_CLIENT_ID: 581005886543-016nfq2fq93sjroi50n8puejk9n1r9h3.apps.googleusercontent.com
      BACKEND_URL_DEV: https://ebook.workon.space
      ADMIN_URL_DEV: https://ebook.workon.space
      FRONTEND_URL_DEV: https://ebook.workon.space
      ALLOW_ORIGIN_TOKEN: huonglienhcmutefit123

  admin:
    image: qhuong1008/mori-admin
    networks:
      - backend_network
    environment:
      REACT_APP_BACKEND_URL: https://ebook.workon.space
      REACT_APP_FRONTEND_URL: https://ebook.workon.space
      REACT_APP_ADMIN_URL: https://ebook.workon.space
      REACT_APP_ALLOW_ORIGIN_TOKEN: huonglienhcmutefit123
      REACT_APP_JWT_SECRET: hcmutefitmoriauth

  nlp:
    image: qhuong1008/mori-nlp
    networks:
      - backend_network
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    networks:
      - backend_network
    ports:
      - 10047:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  backend_network:
